version: '3.8'
services:
  db:
    image: postgres:16 # Use a version that matches your Render database if possible
    container_name: my-music-app-postgres
    environment:
      POSTGRES_DB: music_app_db # Must match the 'Database' name you chose on Render
      POSTGRES_USER: music_user # Must match the 'User' name you chose on Render
      POSTGRES_PASSWORD: mysecretpassword # Choose a strong password for local dev
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for your local data

  app:
    build: .
    container_name: music-application
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/music_app_db
      SPRING_DATASOURCE_USERNAME: music_user
      SPRING_DATASOURCE_PASSWORD: mysecretpassword

volumes:
  postgres_data: